name = "Funky Senior MC"
author = "FunkyChickenMC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a482e4dbf1ccbbf6c6c37c9a102102bc5b9046c1cee1bbe491b72bfd8e0b425"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
