name = "Funky Senior MC"
author = "FunkyChickenMC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ad47289eda45467596a7a3f50160fcf3ae97ffed54b9426b9af4e9174881a32"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
