name = "Funky Senior MC"
author = "FunkyChickenMC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee6880f0afb5318c4ae5a354ff0fda6abc00adb75389a7754ebb67ddb5e3650f"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
