name = "Funky Senior MC"
author = "FunkyChickenMC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a626529e592a2aff515b7f17d8a656f5537b38cc66b427f879412ce053669f0c"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
