name = "Funky Senior MC"
author = "FunkyChickenMC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9b94ea6194695214559ccdd6b28a1b3ce46e8eff91867d23568b0919138c3af"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
