name = "Funky Senior MC"
author = "FunkyChickenMC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69f63854689a359c2ad87fd535002f8bf1dfe48e7d5deb34676d0c67ea0befd4"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
